name: "nodejs-binaries"
base: "core22"
summary: "Node.js binaries"
description: |
  This snap provides prebuilt Node.js binaries. This is mostly intended to be
  included as a build dependency in other snaps to save compile time on
  platforms that do not have pre-built Node.js packages available. As such,
  the usespace components included are not tested outside of this use-case.
confinement: "strict"
license: "MIT AND BSD-2-Clause AND ISC"
issues: "https://github.com/IsaacJT/nodejs-binaries-snap/issues"
website: "https://github.com/IsaacJT/nodejs-binaries-snap"
source-code: "https://github.com/IsaacJT/nodejs-binaries-snap"
contact: "isaac.true@canonical.com"
version: "v16.20.2"

parts:
  nodejs:
    plugin: "autotools"
    source: "https://github.com/nodejs/node.git"
    source-tag: "v16.20.2"
    source-type: "git"
    source-depth: 1
    build-packages:
      - "python3"
      - "python3-pip"
      - "make"
      - "libatomic1"
      - "libssl-dev"
      - "gcc-10"
      - "g++-10"
    stage-packages:
      - "libstdc++6"
      - "libssl3"
    build-environment:
      - CC: "gcc-10"
      - CXX: "g++-10"
    autotools-configure-parameters:
      - "--shared-openssl"
      - "--prefix=/usr"

  npmrc:
    plugin: "nil"
    override-build: |
      mkdir -p "${CRAFT_PART_INSTALL}/etc"
      echo "prefix = /usr" >> "${CRAFT_PART_INSTALL}/etc/npmrc"

apps:
  npm:
    command: "usr/bin/npm"
    plugs:
      - "home"
      - "network"
  corepack:
    command: "usr/bin/corepack"
    plugs:
      - "home"
      - "network"
  npx:
    command: "usr/bin/npx"
    plugs:
      - "home"
      - "network"
  node:
    command: "usr/bin/node"
    plugs:
      - "home"
      - "network"
      - "network-bind"

layout:
  /usr:
    bind: "$SNAP/usr"
